### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by scientistkev** [SincerelyBrittany/SincerelyBrittany#1]
Hey Brittany! I saw that you followed me a while back and you're (in? graduated from?) Flatiron School. I am finishing the Data Science Bootcamp tomorrow :-) let me know if you ever wanna collab on something!

**Comment by SincerelyBrittany** [comment]
Hi @scientistkev CONGRATULATIONS ON GRADUATING! 🎉  I am definitely interested in collaborating! I do not finish my program until December, but I am always open to learning with others. Do you have anything in mind? and are you on the Flatiron slack channel?

**Comment by scientistkev** [comment]
Yep! Send me a message and we can brainstorm ideas! My Slack name is Kevin McPherson :-)
